Repository NTI-Gymnasieingenjor/lunchpad, pull requests merged in 2020-11, with the labels that each got.

#11 Save lunch data feature
  lunchpad.py
  test_saves_data.py
Labels: enhancement

#19 Fix bugs in lunchpad
  lunchpad.py
  test_saves_data.py
Labels: bug, enhancement

#23 Upload data feature
  .gitignore
  test_upload_data.py
  upload_data.py
Labels: enhancement

#38 Fix character bug when saving data
  lunchpad.py
Labels: bug

#40 Fix timeout bug
  upload_data.py
Labels: bug

#44 Fixed the path to the denied.mp3 sound file
  lunchpad.py
Labels: bug

#48 Specialcase feature
  .gitignore
  download_data.py
  lunchpad.py
  test_specialcase.py
Labels: enhancement

#50 Fix no specialcase.csv file bug
  lunchpad.py
Labels: bug

#51 Fix bugs in saves data
  lunchpad.py
  test_saves_data.py
Labels: bug
